Criando camada de requisição e botão em RX
devpass-tech/challenge-reactive-ios pull request #2
Opened 2022-11-08 20:32 UTC by esmedeiros

Criando camada da home com RX e botão na tela de detalhes.

2022-11-08 20:46 UTC, reisdev requested changes

2022-11-08 20:46 UTC, reisdev commented on solutions/devsprint-matheus-reis-5/FinanceApp/Modules/Home/HomeViewController.swift
> +
Essas 2 linhas extras podem ser removidas

2022-11-08 20:46 UTC, reisdev commented on solutions/devsprint-matheus-reis-5/FinanceApp/Modules/Home/HomeViewController.swift
> +    init(withService service: FinanceService = FinanceService()) {
Por se tratar de um método `init`, o parâmetro `service` aqui poderia ser declarado apenas como:

```swift
init(service: FinanceService = FinanceService())
```

Caso fosse parte de outro método qualquer, geralmente aplicamos o label `with` dessa forma:

```swift
func myMethod(with service: FinanceService) {
    // ...
}

// na hora de usar, ficaria assim:
foo.myMethod(with: service)
```

2022-11-10 21:17 UTC, esmedeiros commented on solutions/devsprint-matheus-reis-5/FinanceApp/Modules/Home/HomeViewController.swift
> +
Feito!

2022-11-10 21:18 UTC, esmedeiros commented on solutions/devsprint-matheus-reis-5/FinanceApp/Modules/Home/HomeViewController.swift
> +    init(withService service: FinanceService = FinanceService()) {
muito obrigado, realmente não tem a necessidade desse with, comi bola. =-)

2022-11-10 22:33 UTC, reisdev approved these changes

2022-11-10 22:33 UTC, merged